-- =============================================================================
-- File: sql/16_capstones/anomaly_detection_patterns.sql
-- Capstone: anomaly detection in pure SQL, scored against planted ground truth
-- =============================================================================
-- What this capstone teaches
--   * Window-function statistics: RANGE frames over timestamps, EXCLUDE CURRENT
--     ROW, FILTER inside window aggregates, centred frames.
--   * Robust statistics with ordered-set aggregates (median / MAD via
--     percentile_cont) and why they beat mean/stddev when data is contaminated.
--   * Seasonal baselines (sensor x hour-of-week) plus a local-level correction:
--     a poor man's STL decomposition in SQL.
--   * Contextual (level-shift) detection with a persistence rule and with a
--     custom CUSUM aggregate used as a window function.
--   * Honest evaluation: every detector is scored against meta.ground_truth with
--     TP / FP / FN, precision, recall and F1, per detector and per label, in one
--     comparison table.
--
-- Ground truth (generated by sql/03_dml_queries/seed_data.sql, see
-- meta.planted_effects):
--   mobility.sensor_readings  spike        ~0.4% of readings, +24 units (+2.5x+240 for traffic)
--                             dropout      ~0.2%, value forced to 0, data_quality_score 0.25
--                             level_shift  3 windows per sensor, 6-24 h, value x1.4
--   commerce.orders           order_amount_outlier  ~0.2% of orders, item prices x15-25
--
-- All objects live in schema anomaly_detection and are (re)created idempotently.
-- Only base tables are READ; nothing in the base schemas is modified.
-- =============================================================================

\echo '== 0. Schema and tunable detector configuration'
CREATE SCHEMA IF NOT EXISTS anomaly_detection;
COMMENT ON SCHEMA anomaly_detection IS
    'Capstone 16: SQL anomaly detectors over sensor readings and orders, evaluated against meta.ground_truth.';

-- Thresholds live in a table, not in code, so a learner can UPDATE them and
-- simply re-query the evaluation views (they are plain views over the scores).
CREATE TABLE IF NOT EXISTS anomaly_detection.detector_config (
    detector     text PRIMARY KEY,
    threshold    float8 NOT NULL,
    description  text NOT NULL
);
INSERT INTO anomaly_detection.detector_config (detector, threshold, description) VALUES
    ('quality_flag',      0.50, 'Rule: data_quality_score below threshold => dropout (uses sensor metadata, not the value).'),
    ('rolling_z',         3.50, 'Trailing 24 h mean/stddev z-score (frame excludes the current row).'),
    ('robust_mad',        3.50, 'Per-sensor median / MAD robust z-score, no seasonality.'),
    ('seasonal_mad',      3.50, 'Sensor x hour-of-week median baseline + local level, MAD-scaled residual.'),
    ('level_persistence', 2.00, 'Centred 7 h mean of clipped seasonal z >= threshold AND point z >= threshold.'),
    ('cusum',             8.00, 'Two-sided CUSUM (k = 1) on seasonal z, capped; alarm when S >= threshold.'),
    ('ensemble',          5.00, 'level_persistence => level_shift, else seasonal z (stricter) => spike/dropout.')
ON CONFLICT (detector) DO UPDATE           -- re-running the file restores the defaults
    SET threshold = EXCLUDED.threshold, description = EXCLUDED.description;

-- -----------------------------------------------------------------------------
-- 1. A custom aggregate usable as a window function: CUSUM
-- -----------------------------------------------------------------------------
-- Teaches: CREATE AGGREGATE with a state transition function. Any aggregate can
-- be used with OVER (...), so a running aggregate over an ORDER BY frame gives
-- the recursive CUSUM statistic S_t = min(cap, max(0, S_{t-1} + x_t - k))
-- without a recursive CTE. The cap stops S from "remembering" a long shift for
-- days after it ends (the classic weakness of an un-reset CUSUM).
\echo '== 1. CUSUM aggregate'
CREATE OR REPLACE FUNCTION anomaly_detection.cusum_step(s float8, x float8, k float8, cap float8)
RETURNS float8
LANGUAGE sql IMMUTABLE PARALLEL SAFE
RETURN least(cap, greatest(0, coalesce(s, 0) + coalesce(x, 0) - k));

DROP AGGREGATE IF EXISTS anomaly_detection.cusum(float8, float8, float8);
CREATE AGGREGATE anomaly_detection.cusum(float8, float8, float8) (
    SFUNC    = anomaly_detection.cusum_step,
    STYPE    = float8,
    INITCOND = '0'
);
COMMENT ON AGGREGATE anomaly_detection.cusum(float8, float8, float8) IS
    'Upper CUSUM: cusum(x, k, cap). Use as a running window aggregate ORDER BY time.';

-- -----------------------------------------------------------------------------
-- 2. Feature table: one row per reading with every detector's score
-- -----------------------------------------------------------------------------
-- Teaches: building features in stages with CTEs:
--   (a) trailing-window stats with RANGE '24 hours' PRECEDING ... EXCLUDE CURRENT ROW
--       (a RANGE frame over timestamptz copes with missing hours; ROWS would not);
--   (b) robust centre/scale with percentile_cont (an ordered-set aggregate,
--       NOT available as a window function, hence the GROUP BY + join);
--   (c) seasonal baseline per sensor x hour-of-week (168 cells, ~13 obs each);
--   (d) local-level correction: centred +/-84 h mean of the seasonal residual,
--       with FILTER to ignore gross outliers (FILTER works in window aggregates),
--       then a residual scale per sensor x hour-of-day, because noise is
--       heteroscedastic (traffic noise is multiplicative: rush-hour residuals
--       are ~8x larger than night-time ones; one pooled MAD floods peak hours
--       with false alarms);
--   (e) CUSUM in both directions on the clipped, standardised residual.
-- A module-owned table (not a matview) keeps the lesson re-runnable cheaply.
\echo '== 2. Building anomaly_detection.sensor_scores (about 103k rows)'
DROP TABLE IF EXISTS anomaly_detection.sensor_scores CASCADE;
CREATE TABLE anomaly_detection.sensor_scores AS
WITH base AS (
    SELECT r.reading_id, r.sensor_code, r.sensor_type, r.reading_time,
           r.reading_value::float8                                       AS v,
           r.data_quality_score::float8                                  AS q,
           ((extract(isodow FROM r.reading_time AT TIME ZONE 'UTC') - 1) * 24
             + extract(hour FROM r.reading_time AT TIME ZONE 'UTC'))::int  AS how
    FROM mobility.sensor_readings r
),
rolling AS (                                   -- (a) trailing 24 h window
    SELECT b.*,
           avg(v)         OVER w24 AS roll_mean,
           stddev_samp(v) OVER w24 AS roll_sd
    FROM base b
    WINDOW w24 AS (PARTITION BY sensor_code ORDER BY reading_time
                   RANGE BETWEEN interval '24 hours' PRECEDING AND CURRENT ROW
                   EXCLUDE CURRENT ROW)
),
sensor_med AS (                                -- (b) robust centre per sensor
    SELECT sensor_code, percentile_cont(0.5) WITHIN GROUP (ORDER BY v) AS med
    FROM base GROUP BY sensor_code
),
sensor_mad AS (
    SELECT b.sensor_code, m.med,
           percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(b.v - m.med)) AS mad
    FROM base b JOIN sensor_med m USING (sensor_code)
    GROUP BY b.sensor_code, m.med
),
how_med AS (                                   -- (c) seasonal baseline
    SELECT sensor_code, how, percentile_cont(0.5) WITHIN GROUP (ORDER BY v) AS how_med
    FROM base GROUP BY sensor_code, how
),
resid1 AS (
    SELECT ro.*, h.how_med, ro.v - h.how_med AS r1
    FROM rolling ro JOIN how_med h USING (sensor_code, how)
),
r1_scale AS (
    SELECT sensor_code, 1.4826 * percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(r1)) AS s1
    FROM resid1 GROUP BY sensor_code
),
leveled AS (                                   -- (d) local level, outliers filtered out
    SELECT x.*,
           coalesce(avg(x.r1) FILTER (WHERE abs(x.r1) < 3 * s.s1) OVER w168, 0) AS local_level
    FROM resid1 x JOIN r1_scale s USING (sensor_code)
    WINDOW w168 AS (PARTITION BY x.sensor_code ORDER BY x.reading_time
                    RANGE BETWEEN interval '84 hours' PRECEDING AND interval '84 hours' FOLLOWING)
),
resid2 AS (
    SELECT l.*, l.r1 - l.local_level AS r2 FROM leveled l
),
r2_scale AS (                                  -- heteroscedastic scale: per sensor x hour-of-day
    SELECT sensor_code, how % 24 AS hod,
           1.4826 * percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(r2)) AS s2
    FROM resid2 GROUP BY sensor_code, how % 24
),
scored AS (
    SELECT r.reading_id, r.sensor_code, r.sensor_type, r.reading_time, r.v, r.q, r.how,
           (r.v - r.roll_mean) / nullif(r.roll_sd, 0)                        AS z_roll,
           0.6745 * (r.v - m.med) / nullif(m.mad, 0)                          AS z_robust,
           r.how_med + r.local_level                                          AS seasonal_expected,
           r.r2 / nullif(s.s2, 0)                                             AS z_seasonal
    FROM resid2 r
    JOIN sensor_mad m USING (sensor_code)
    JOIN r2_scale  s ON s.sensor_code = r.sensor_code AND s.hod = r.how % 24
)
SELECT sc.*,
       -- level-shift persistence: centred 7-hour mean of the clipped z
       avg(greatest(-4, least(4, sc.z_seasonal))) OVER w7               AS z_persist,
       -- (e) two-sided CUSUM (k = 1 sigma, capped at 12)
       anomaly_detection.cusum(greatest(-4, least(4,  sc.z_seasonal)), 1, 12) OVER wrun AS cusum_up,
       anomaly_detection.cusum(greatest(-4, least(4, -sc.z_seasonal)), 1, 12) OVER wrun AS cusum_down
FROM scored sc
WINDOW w7   AS (PARTITION BY sc.sensor_code ORDER BY sc.reading_time
                RANGE BETWEEN interval '3 hours' PRECEDING AND interval '3 hours' FOLLOWING),
       wrun AS (PARTITION BY sc.sensor_code ORDER BY sc.reading_time
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);

ALTER TABLE anomaly_detection.sensor_scores ADD PRIMARY KEY (reading_id);
CREATE INDEX IF NOT EXISTS sensor_scores_sensor_time_idx
    ON anomaly_detection.sensor_scores (sensor_code, reading_time);
ANALYZE anomaly_detection.sensor_scores;

-- Peek at one sensor around a labelled level shift: watch z_persist and cusum_up rise.
SELECT s.sensor_code, s.reading_time, round(s.v::numeric, 1) AS v,
       round(s.seasonal_expected::numeric, 1) AS expected,
       round(s.z_seasonal::numeric, 2) AS z_seas, round(s.z_persist::numeric, 2) AS z_persist,
       round(s.cusum_up::numeric, 1) AS cusum_up, g.label AS truth
FROM anomaly_detection.sensor_scores s
LEFT JOIN meta.ground_truth g ON g.entity = 'mobility.sensor_readings' AND g.entity_id = s.reading_id
WHERE s.sensor_code = 'NOI-001'
  AND s.reading_time BETWEEN (SELECT min(s2.reading_time) - interval '3 hours'
                              FROM anomaly_detection.sensor_scores s2
                              JOIN meta.ground_truth g2 ON g2.entity = 'mobility.sensor_readings'
                                                       AND g2.entity_id = s2.reading_id AND g2.label = 'level_shift'
                              WHERE s2.sensor_code = 'NOI-001')
                         AND (SELECT min(s2.reading_time) + interval '8 hours'
                              FROM anomaly_detection.sensor_scores s2
                              JOIN meta.ground_truth g2 ON g2.entity = 'mobility.sensor_readings'
                                                       AND g2.entity_id = s2.reading_id AND g2.label = 'level_shift'
                              WHERE s2.sensor_code = 'NOI-001')
ORDER BY s.reading_time
LIMIT 12;

-- -----------------------------------------------------------------------------
-- 3. Predictions: each detector assigns at most ONE label per reading
-- -----------------------------------------------------------------------------
-- Teaches: turning scores into decisions in a view driven by the config table,
-- and LATERAL (VALUES ...) to unpivot several detectors into long format.
\echo '== 3. Sensor predictions view'
CREATE OR REPLACE VIEW anomaly_detection.sensor_predictions AS
WITH cfg AS (
    SELECT max(threshold) FILTER (WHERE detector = 'quality_flag')      AS t_q,
           max(threshold) FILTER (WHERE detector = 'rolling_z')         AS t_roll,
           max(threshold) FILTER (WHERE detector = 'robust_mad')        AS t_rob,
           max(threshold) FILTER (WHERE detector = 'seasonal_mad')      AS t_seas,
           max(threshold) FILTER (WHERE detector = 'level_persistence') AS t_lvl,
           max(threshold) FILTER (WHERE detector = 'cusum')             AS t_cus,
           max(threshold) FILTER (WHERE detector = 'ensemble')          AS t_ens
    FROM anomaly_detection.detector_config
)
SELECT s.reading_id, p.detector, p.predicted_label
FROM anomaly_detection.sensor_scores s
CROSS JOIN cfg c
CROSS JOIN LATERAL (VALUES
    ('quality_flag',
        CASE WHEN s.q < c.t_q THEN 'dropout' END),
    ('rolling_z',
        CASE WHEN s.z_roll >=  c.t_roll THEN 'spike'
             WHEN s.z_roll <= -c.t_roll THEN 'dropout' END),
    ('robust_mad',
        CASE WHEN s.z_robust >=  c.t_rob THEN 'spike'
             WHEN s.z_robust <= -c.t_rob THEN 'dropout' END),
    ('seasonal_mad',
        CASE WHEN s.z_seasonal >=  c.t_seas THEN 'spike'
             WHEN s.z_seasonal <= -c.t_seas THEN 'dropout' END),
    ('level_persistence',
        CASE WHEN abs(s.z_persist) >= c.t_lvl AND abs(s.z_seasonal) >= c.t_lvl
              AND sign(s.z_persist) = sign(s.z_seasonal) THEN 'level_shift' END),
    ('cusum',
        CASE WHEN greatest(s.cusum_up, s.cusum_down) >= c.t_cus THEN 'level_shift' END),
    ('ensemble',
        CASE WHEN abs(s.z_persist) >= c.t_lvl AND abs(s.z_seasonal) >= c.t_lvl
              AND sign(s.z_persist) = sign(s.z_seasonal) THEN 'level_shift'
             WHEN s.z_seasonal >=  c.t_ens THEN 'spike'
             WHEN s.z_seasonal <= -c.t_ens THEN 'dropout' END)
) AS p(detector, predicted_label)
WHERE p.predicted_label IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 4. Evaluation against meta.ground_truth: ONE comparison table
-- -----------------------------------------------------------------------------
-- Teaches: confusion-matrix arithmetic with FILTER, a FULL JOIN between
-- predictions and truth, and GROUPING SETS to get per-label rows and an
-- 'ALL (any anomaly)' row per detector in a single pass.
--   per label L: TP = predicted L and truth L
--                FP = predicted L and truth is not L (other label or normal)
--                FN = truth L and not predicted L
--   'ALL' row  : label-agnostic, i.e. "did we flag an anomalous reading at all".
\echo '== 4. Detector x label evaluation (precision / recall / F1)'
CREATE OR REPLACE VIEW anomaly_detection.sensor_evaluation AS
WITH truth AS (
    SELECT entity_id AS reading_id, label AS true_label
    FROM meta.ground_truth
    WHERE entity = 'mobility.sensor_readings'
),
detectors AS (
    SELECT detector FROM anomaly_detection.detector_config
),
-- For each detector, FULL JOIN its predictions with the truth so that missed
-- anomalies (FN) and false alarms (FP) both appear exactly once.
long AS (
    SELECT d.detector, x.reading_id, x.predicted_label, x.true_label
    FROM detectors d
    CROSS JOIN LATERAL (
        SELECT coalesce(p.reading_id, t.reading_id) AS reading_id, p.predicted_label, t.true_label
        FROM (SELECT reading_id, predicted_label FROM anomaly_detection.sensor_predictions
              WHERE detector = d.detector) p
        FULL JOIN truth t ON t.reading_id = p.reading_id
    ) x
),
per_label AS (
    SELECT l.detector, lab.label,
           count(*) FILTER (WHERE l.predicted_label = lab.label AND l.true_label = lab.label)                       AS tp,
           count(*) FILTER (WHERE l.predicted_label = lab.label AND l.true_label IS DISTINCT FROM lab.label)        AS fp,
           count(*) FILTER (WHERE l.true_label = lab.label AND l.predicted_label IS DISTINCT FROM lab.label)        AS fn
    FROM long l
    CROSS JOIN (VALUES ('spike'), ('dropout'), ('level_shift')) lab(label)
    GROUP BY l.detector, lab.label
),
any_label AS (
    SELECT l.detector, 'ALL (any anomaly)'::text AS label,
           count(*) FILTER (WHERE l.predicted_label IS NOT NULL AND l.true_label IS NOT NULL) AS tp,
           count(*) FILTER (WHERE l.predicted_label IS NOT NULL AND l.true_label IS NULL)     AS fp,
           count(*) FILTER (WHERE l.predicted_label IS NULL AND l.true_label IS NOT NULL)     AS fn
    FROM long l
    GROUP BY l.detector
),
u AS (
    SELECT * FROM per_label UNION ALL SELECT * FROM any_label
)
SELECT detector, label, tp, fp, fn,
       round(tp::numeric / nullif(tp + fp, 0), 3)          AS precision,
       round(tp::numeric / nullif(tp + fn, 0), 3)          AS recall,
       round(2.0 * tp / nullif(2 * tp + fp + fn, 0), 3)    AS f1
FROM u;

-- A detector that never predicts a label gets precision NULL and recall 0 for
-- it; that is expected (e.g. rolling_z never says 'level_shift'), so those
-- rows are hidden below. Things to notice:
--   * quality_flag is perfect on dropouts: the generator stamps quality 0.25.
--     Always check the metadata before building a clever model.
--   * point detectors label level-shift readings as 'spike' (FP for spike, FN
--     for level_shift); the ensemble fixes that by testing persistence first.
--   * remaining spike FPs are mostly traffic counters, whose noise is
--     multiplicative; modelling ln(value) for them is a good exercise.
SELECT e.*
FROM anomaly_detection.sensor_evaluation e
JOIN anomaly_detection.detector_config c USING (detector)
WHERE e.tp + e.fp > 0 OR e.label = 'ALL (any anomaly)'
ORDER BY CASE e.label WHEN 'spike' THEN 1 WHEN 'dropout' THEN 2 WHEN 'level_shift' THEN 3 ELSE 4 END,
         e.f1 DESC NULLS LAST, e.detector;

-- Why the naive detectors lose: their recall on spikes by sensor type.
-- Rolling stddev over 24 h is inflated by the diurnal cycle (and by the spike's
-- own neighbours); robust_mad ignores seasonality, so a 6 am spike that is
-- still below the daily peak goes unnoticed.
\echo '== 4b. Spike recall by sensor type and detector'
SELECT s.sensor_type,
       count(*) AS spikes,
       round(avg((s.z_roll     >= 3.5)::int), 3) AS recall_rolling_z,
       round(avg((s.z_robust   >= 3.5)::int), 3) AS recall_robust_mad,
       round(avg((s.z_seasonal >= 3.5)::int), 3) AS recall_seasonal_mad
FROM anomaly_detection.sensor_scores s
JOIN meta.ground_truth g ON g.entity = 'mobility.sensor_readings' AND g.entity_id = s.reading_id AND g.label = 'spike'
GROUP BY s.sensor_type
ORDER BY s.sensor_type;

-- Threshold sweep for the seasonal detector (all labels pooled): the
-- precision/recall trade-off in one query, using generate_series as a grid.
\echo '== 4c. Threshold sweep: seasonal_mad, any anomaly'
WITH truth AS (
    SELECT entity_id AS reading_id FROM meta.ground_truth WHERE entity = 'mobility.sensor_readings'
)
SELECT t.thr,
       count(*) FILTER (WHERE abs(s.z_seasonal) >= t.thr AND tr.reading_id IS NOT NULL) AS tp,
       count(*) FILTER (WHERE abs(s.z_seasonal) >= t.thr AND tr.reading_id IS NULL)     AS fp,
       round(count(*) FILTER (WHERE abs(s.z_seasonal) >= t.thr AND tr.reading_id IS NOT NULL)::numeric
             / nullif(count(*) FILTER (WHERE abs(s.z_seasonal) >= t.thr), 0), 3)         AS precision,
       round(count(*) FILTER (WHERE abs(s.z_seasonal) >= t.thr AND tr.reading_id IS NOT NULL)::numeric
             / (SELECT count(*) FROM truth), 3)                                         AS recall
FROM generate_series(2.5, 6.0, 0.5) AS t(thr)
CROSS JOIN anomaly_detection.sensor_scores s
LEFT JOIN truth tr USING (reading_id)
GROUP BY t.thr
ORDER BY t.thr;

-- -----------------------------------------------------------------------------
-- 5. Commerce: order-amount outliers
-- -----------------------------------------------------------------------------
-- Teaches: choosing the right scale and the right peer group.
--   * global_z      : (total - mean) / sd over ALL orders. Amounts are
--                     log-normal and business types differ by ~10x, so this
--                     mostly flags ordinary technology orders.
--   * tukey_iqr     : Q3 + 3 * IQR fence per business type on the raw amount.
--   * log_robust_z  : median/MAD z of ln(total_amount) per business type.
--   * price_robust_z: median/MAD z of ln(max unit price in the order) per business
--                     type. The injection multiplies item PRICES, so a feature
--                     that removes basket-size noise separates best.
\echo '== 5. Order-amount outlier detectors'
CREATE OR REPLACE VIEW anomaly_detection.order_scores AS
WITH o AS (
    SELECT o.order_id, m.business_type, o.total_amount::float8 AS amt,
           ln(nullif(o.total_amount, 0)::float8) AS ln_amt,
           ln(nullif(i.max_price, 0)::float8)    AS ln_price
    FROM commerce.orders o
    JOIN commerce.merchants m USING (merchant_id)
    JOIN LATERAL (SELECT max(oi.unit_price) AS max_price
                  FROM commerce.order_items oi WHERE oi.order_id = o.order_id) i ON true
    WHERE o.total_amount > 0
),
g AS (
    SELECT avg(amt) AS mu, stddev_samp(amt) AS sd FROM o
),
bt AS (
    SELECT business_type,
           percentile_cont(0.25) WITHIN GROUP (ORDER BY amt)      AS q1,
           percentile_cont(0.75) WITHIN GROUP (ORDER BY amt)      AS q3,
           percentile_cont(0.5)  WITHIN GROUP (ORDER BY ln_amt)   AS med_ln_amt,
           percentile_cont(0.5)  WITHIN GROUP (ORDER BY ln_price) AS med_ln_price
    FROM o GROUP BY business_type
),
bt_mad AS (
    SELECT o.business_type,
           percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(o.ln_amt   - bt.med_ln_amt))   AS mad_ln_amt,
           percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(o.ln_price - bt.med_ln_price)) AS mad_ln_price
    FROM o JOIN bt USING (business_type) GROUP BY o.business_type
)
SELECT o.order_id, o.business_type, o.amt,
       (o.amt - g.mu) / g.sd                                                    AS z_global,
       (o.amt - bt.q3) / nullif(bt.q3 - bt.q1, 0)                               AS iqr_excess,
       0.6745 * (o.ln_amt   - bt.med_ln_amt)   / nullif(m.mad_ln_amt, 0)        AS z_log_amt,
       0.6745 * (o.ln_price - bt.med_ln_price) / nullif(m.mad_ln_price, 0)      AS z_log_price
FROM o CROSS JOIN g JOIN bt USING (business_type) JOIN bt_mad m USING (business_type);

WITH truth AS (
    SELECT entity_id AS order_id FROM meta.ground_truth
    WHERE entity = 'commerce.orders' AND label = 'order_amount_outlier'
),
flags AS (
    SELECT s.order_id, d.detector, d.flagged
    FROM anomaly_detection.order_scores s
    CROSS JOIN LATERAL (VALUES
        ('global_z > 3',          s.z_global    > 3),
        ('tukey_iqr Q3+3*IQR',    s.iqr_excess  > 3),
        ('log_robust_z > 3.5',    s.z_log_amt   > 3.5),
        ('price_robust_z > 3.5',  s.z_log_price > 3.5)
    ) d(detector, flagged)
)
SELECT f.detector, 'order_amount_outlier' AS label,
       count(*) FILTER (WHERE f.flagged AND t.order_id IS NOT NULL)          AS tp,
       count(*) FILTER (WHERE f.flagged AND t.order_id IS NULL)              AS fp,
       count(*) FILTER (WHERE NOT f.flagged AND t.order_id IS NOT NULL)      AS fn,
       round(count(*) FILTER (WHERE f.flagged AND t.order_id IS NOT NULL)::numeric
             / nullif(count(*) FILTER (WHERE f.flagged), 0), 3)             AS precision,
       round(count(*) FILTER (WHERE f.flagged AND t.order_id IS NOT NULL)::numeric
             / nullif(count(t.order_id), 0), 3)                             AS recall,
       round(2.0 * count(*) FILTER (WHERE f.flagged AND t.order_id IS NOT NULL)
             / nullif(count(*) FILTER (WHERE f.flagged) + count(t.order_id), 0), 3) AS f1
FROM flags f
LEFT JOIN truth t USING (order_id)
GROUP BY f.detector
ORDER BY f1 DESC NULLS LAST, f.detector;

-- -----------------------------------------------------------------------------
-- 6. Rule-based behavioural checks (no ground truth: triage lists)
-- -----------------------------------------------------------------------------
-- Teaches: not every anomaly has a label. These rules produce ranked review
-- queues; their "precision" can only be measured by human investigation.
-- Recency windows use meta.as_of(), the dataset's reference "now".
\echo '== 6. Behavioural rule: self-dealing and bursty ordering (top 5)'
CREATE OR REPLACE VIEW anomaly_detection.order_behaviour_flags AS
SELECT o.customer_citizen_id,
       o.merchant_id,
       count(*)                                                    AS orders_90d,
       sum(o.total_amount)                                         AS spend_90d,
       bool_or(o.customer_citizen_id = m.owner_citizen_id)         AS self_dealing,
       min(o.order_date - lag_date)                                AS min_gap
FROM (
    SELECT o.*, lag(o.order_date) OVER (PARTITION BY o.customer_citizen_id, o.merchant_id
                                        ORDER BY o.order_date, o.order_id) AS lag_date
    FROM commerce.orders o
    WHERE o.order_date >= meta.as_of() - interval '90 days'
) o
JOIN commerce.merchants m USING (merchant_id)
GROUP BY o.customer_citizen_id, o.merchant_id
HAVING bool_or(o.customer_citizen_id = m.owner_citizen_id)
    OR min(o.order_date - lag_date) < interval '10 minutes'
    OR count(*) >= 6;

SELECT * FROM anomaly_detection.order_behaviour_flags
ORDER BY self_dealing DESC, orders_90d DESC, customer_citizen_id, merchant_id
LIMIT 5;

-- -----------------------------------------------------------------------------
-- 7. Experiment: change a threshold, the evaluation follows
-- -----------------------------------------------------------------------------
-- Teaches: because predictions/evaluation are views over a config table, a
-- what-if is one UPDATE inside a transaction that we roll back.
\echo '== 7. What-if: seasonal_mad threshold 3.5 -> 5.0 (rolled back)'
BEGIN;
UPDATE anomaly_detection.detector_config SET threshold = 5.0 WHERE detector = 'seasonal_mad';
SELECT detector, label, tp, fp, fn, precision, recall, f1
FROM anomaly_detection.sensor_evaluation
WHERE detector = 'seasonal_mad' AND label IN ('spike', 'dropout', 'ALL (any anomaly)')
ORDER BY label;
ROLLBACK;
