-- File: sql/12_security_rls/rls_policies.sql
-- Purpose: Row-level security (RLS) for multi-tenant data isolation
--
-- What this module teaches
--   1. Session context: SET ROLE + set_config('app.current_tenant', ...) as the tenant key
--   2. Per-command policies: USING (which rows are visible) vs WITH CHECK (which rows may be written)
--   3. PERMISSIVE policies are OR-ed together; RESTRICTIVE policies are AND-ed on top of them
--   4. Who bypasses RLS: superusers and BYPASSRLS roles always; the table OWNER unless FORCE ROW LEVEL SECURITY
--   5. Pitfalls: empty-string GUCs, "default deny", and views that run with the owner's rights
--
-- Safety: all demo data lives in the module-owned schema rls_demo (rebuilt on every run).
-- The one demo on a shared base table (civics.citizens) runs inside BEGIN ... ROLLBACK.
-- Roles are cluster-global, so the extra demo roles are created idempotently and never dropped.

\echo '== 12 / RLS: setup =='

-- =============================================================================
-- 0. DEMO ROLES (cluster-global, created idempotently)
-- =============================================================================
-- rls_tenant_user : what the application connects as (NOLOGIN here; SET ROLE to it)
-- rls_table_owner : a NON-superuser owner, so we can show the owner bypass and FORCE RLS
-- rls_auditor     : a role that a restrictive policy lets see sensitive rows
DO $$
DECLARE r TEXT;
BEGIN
    FOREACH r IN ARRAY ARRAY['rls_tenant_user', 'rls_table_owner', 'rls_auditor'] LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            BEGIN
                EXECUTE format('CREATE ROLE %I NOLOGIN', r);
            EXCEPTION WHEN duplicate_object THEN
                NULL;  -- another session created it concurrently
            END;
        END IF;
    END LOOP;
END $$;

-- =============================================================================
-- 1. MODULE-OWNED MULTI-TENANT TABLES
-- =============================================================================
-- Tenants are the 24 neighbourhood councils; each council may only see the
-- service requests filed in its own neighbourhood.
DROP SCHEMA IF EXISTS rls_demo CASCADE;
CREATE SCHEMA rls_demo;

CREATE TABLE rls_demo.tenants (
    tenant_id     INTEGER PRIMARY KEY,
    tenant_name   TEXT NOT NULL
);

INSERT INTO rls_demo.tenants (tenant_id, tenant_name)
SELECT neighborhood_id, neighborhood_name || ' Council'
FROM geo.neighborhood_boundaries
ORDER BY neighborhood_id;

CREATE TABLE rls_demo.service_requests (
    request_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           INTEGER NOT NULL REFERENCES rls_demo.tenants,
    reporter_citizen_id BIGINT,
    category            TEXT NOT NULL,
    priority_level      TEXT NOT NULL,
    status              TEXT NOT NULL,
    is_sensitive        BOOLEAN NOT NULL DEFAULT false,   -- e.g. safety reports; auditors only
    submitted_at        TIMESTAMPTZ NOT NULL
);

-- Copy the base complaints into the module table (the base table is never touched).
INSERT INTO rls_demo.service_requests
    (request_id, tenant_id, reporter_citizen_id, category, priority_level, status, is_sensitive, submitted_at)
SELECT complaint_id, neighborhood_id, reporter_citizen_id, category,
       priority_level::TEXT, status::TEXT,
       priority_level = 'urgent',              -- treat urgent reports as sensitive
       submitted_at
FROM documents.complaint_records
ORDER BY complaint_id;

SELECT setval(pg_get_serial_sequence('rls_demo.service_requests', 'request_id'),
              (SELECT max(request_id) FROM rls_demo.service_requests));

-- Index the tenant key: every RLS-filtered query gets "tenant_id = <constant>" added.
CREATE INDEX ON rls_demo.service_requests (tenant_id);

-- Hand the table to a non-superuser owner (see section 5).
ALTER TABLE rls_demo.service_requests OWNER TO rls_table_owner;
ALTER TABLE rls_demo.tenants          OWNER TO rls_table_owner;

GRANT USAGE ON SCHEMA rls_demo TO rls_tenant_user, rls_table_owner, rls_auditor;
GRANT SELECT ON rls_demo.tenants TO rls_tenant_user, rls_auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON rls_demo.service_requests TO rls_tenant_user;
GRANT SELECT ON rls_demo.service_requests TO rls_auditor;
-- rls_auditor also "is" a tenant user for the demo
GRANT rls_tenant_user TO rls_auditor;

-- =============================================================================
-- 2. CONTEXT HELPERS
-- =============================================================================
-- The tenant id travels in a custom GUC.  Two subtleties:
--   * current_setting('x', true) returns NULL if the GUC was never set, but ''
--     after it has been set and RESET in the same session -> ''::int would ERROR.
--     NULLIF(..., '') makes both cases NULL, and "tenant_id = NULL" matches nothing
--     (fail closed).
--   * Wrapping the call in a STABLE function lets the planner evaluate it once.
CREATE OR REPLACE FUNCTION rls_demo.current_tenant()
RETURNS INTEGER
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT NULLIF(current_setting('app.current_tenant', true), '')::INTEGER $$;

CREATE OR REPLACE FUNCTION rls_demo.set_tenant(p_tenant INTEGER, p_local BOOLEAN DEFAULT false)
RETURNS VOID
LANGUAGE sql
AS $$ SELECT set_config('app.current_tenant', COALESCE(p_tenant::TEXT, ''), p_local) $$;
-- Use p_local => true (SET LOCAL semantics) with connection pools in transaction mode,
-- so the tenant cannot leak into the next transaction that reuses the connection.

GRANT EXECUTE ON FUNCTION rls_demo.current_tenant() TO rls_tenant_user, rls_table_owner, rls_auditor;
GRANT EXECUTE ON FUNCTION rls_demo.set_tenant(INTEGER, BOOLEAN) TO rls_tenant_user, rls_table_owner, rls_auditor;

-- =============================================================================
-- 3. ENABLE RLS + PERMISSIVE POLICIES
-- =============================================================================
-- With RLS enabled and NO policy, non-owners see zero rows ("default deny").
ALTER TABLE rls_demo.service_requests ENABLE ROW LEVEL SECURITY;

\echo '-- default deny: RLS enabled, no policies yet -> 0 rows for the tenant user'
SET ROLE rls_tenant_user;
SELECT rls_demo.set_tenant(1);
SELECT count(*) AS visible_with_no_policy FROM rls_demo.service_requests;
RESET ROLE;

-- Permissive policy per command.  USING filters existing rows; WITH CHECK validates new rows.
CREATE POLICY tenant_select ON rls_demo.service_requests
    AS PERMISSIVE FOR SELECT TO rls_tenant_user
    USING (tenant_id = (SELECT rls_demo.current_tenant()));   -- (SELECT ...) => evaluated once (InitPlan)

CREATE POLICY tenant_insert ON rls_demo.service_requests
    AS PERMISSIVE FOR INSERT TO rls_tenant_user
    WITH CHECK (tenant_id = (SELECT rls_demo.current_tenant()));

CREATE POLICY tenant_update ON rls_demo.service_requests
    AS PERMISSIVE FOR UPDATE TO rls_tenant_user
    USING      (tenant_id = (SELECT rls_demo.current_tenant()))  -- which rows you may target
    WITH CHECK (tenant_id = (SELECT rls_demo.current_tenant())); -- what they may become

CREATE POLICY tenant_delete ON rls_demo.service_requests
    AS PERMISSIVE FOR DELETE TO rls_tenant_user
    USING (tenant_id = (SELECT rls_demo.current_tenant()) AND status = 'draft');

-- A second PERMISSIVE SELECT policy is OR-ed with the first: everyone may also read
-- resolved/archived requests from any neighbourhood (public transparency).
CREATE POLICY public_resolved_select ON rls_demo.service_requests
    AS PERMISSIVE FOR SELECT TO rls_tenant_user
    USING (status IN ('resolved', 'archived'));

-- =============================================================================
-- 4. RESTRICTIVE POLICY (AND-ed on top of the permissive ones)
-- =============================================================================
-- Sensitive rows are hidden from everybody except members of rls_auditor, no matter
-- which permissive policy matched.  A restrictive policy alone grants nothing:
-- at least one permissive policy must also pass.
CREATE POLICY hide_sensitive ON rls_demo.service_requests
    AS RESTRICTIVE FOR SELECT TO rls_tenant_user
    USING (NOT is_sensitive OR pg_has_role(current_user, 'rls_auditor', 'MEMBER'));

\echo '-- policies on rls_demo.service_requests'
SELECT policyname, permissive, cmd, roles, qual, with_check
FROM pg_policies
WHERE schemaname = 'rls_demo' AND tablename = 'service_requests'
ORDER BY policyname;

-- =============================================================================
-- 5. POLICIES IN ACTION: SET ROLE + set_config
-- =============================================================================
\echo '-- what each identity sees'
-- Ground truth computed as superuser (no RLS) for comparison
SELECT tenant_id,
       count(*)                                        AS all_rows,
       count(*) FILTER (WHERE NOT is_sensitive)        AS non_sensitive,
       (SELECT count(*) FROM rls_demo.service_requests s2
         WHERE s2.status IN ('resolved','archived') AND NOT s2.is_sensitive) AS public_non_sensitive_all_tenants
FROM rls_demo.service_requests
WHERE tenant_id IN (1, 2)
GROUP BY tenant_id
ORDER BY tenant_id;

-- Tenant 1, ordinary user: own non-sensitive rows + public resolved rows from all tenants
SET ROLE rls_tenant_user;
SELECT rls_demo.set_tenant(1);
SELECT 'tenant 1 / app user' AS identity,
       count(*)                                    AS visible_rows,
       count(*) FILTER (WHERE tenant_id = 1)       AS own_tenant_rows,
       count(*) FILTER (WHERE tenant_id <> 1)      AS other_tenant_rows_public,
       count(*) FILTER (WHERE is_sensitive)        AS sensitive_rows
FROM rls_demo.service_requests;

-- No tenant set: only the public policy matches (fail closed for private rows)
SELECT rls_demo.set_tenant(NULL);
SELECT 'no tenant / app user' AS identity,
       count(*) AS visible_rows,
       count(*) FILTER (WHERE status NOT IN ('resolved','archived')) AS private_rows_leaked
FROM rls_demo.service_requests;
RESET ROLE;

-- Auditor (member of rls_tenant_user, so the same policies apply) also sees sensitive rows
SET ROLE rls_auditor;
SELECT rls_demo.set_tenant(1);
SELECT 'tenant 1 / auditor' AS identity,
       count(*) AS visible_rows,
       count(*) FILTER (WHERE is_sensitive) AS sensitive_rows
FROM rls_demo.service_requests;
RESET ROLE;

-- How the policy shows up in a plan: the tenant filter is injected into the scan.
SET ROLE rls_tenant_user;
SELECT rls_demo.set_tenant(1);
EXPLAIN (COSTS OFF)
SELECT * FROM rls_demo.service_requests WHERE category = 'Noise';
RESET ROLE;

-- =============================================================================
-- 6. WITH CHECK: writes are validated against the policy
-- =============================================================================
\echo '-- WITH CHECK in action (inside a rolled-back transaction)'
BEGIN;
SET LOCAL ROLE rls_tenant_user;
SELECT rls_demo.set_tenant(3, true);

-- Allowed: inserting into my own tenant
INSERT INTO rls_demo.service_requests (tenant_id, category, priority_level, status, submitted_at)
VALUES (3, 'Noise', 'low', 'draft', now())
RETURNING request_id > 0 AS inserted_own_tenant;

-- Rejected: inserting into another tenant violates WITH CHECK
DO $$
BEGIN
    INSERT INTO rls_demo.service_requests (tenant_id, category, priority_level, status, submitted_at)
    VALUES (4, 'Noise', 'low', 'draft', now());
    RAISE NOTICE 'unexpected: cross-tenant insert succeeded';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'cross-tenant INSERT blocked: %', SQLERRM;
END $$;

-- Rejected: moving my row to another tenant (UPDATE WITH CHECK)
DO $$
BEGIN
    UPDATE rls_demo.service_requests SET tenant_id = 4
    WHERE tenant_id = 3 AND status = 'draft';
    RAISE NOTICE 'unexpected: tenant hop succeeded';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'tenant-hopping UPDATE blocked: %', SQLERRM;
END $$;

-- Silently filtered (NOT an error): UPDATE/DELETE of rows you cannot see touch 0 rows.
WITH upd AS (
    UPDATE rls_demo.service_requests SET status = 'archived'
    WHERE tenant_id = 5 AND status NOT IN ('resolved','archived')
    RETURNING 1
)
SELECT count(*) AS other_tenant_rows_updated FROM upd;
ROLLBACK;

-- =============================================================================
-- 7. WHO BYPASSES RLS: superuser, BYPASSRLS, and the owner (unless FORCE)
-- =============================================================================
\echo '-- bypass rules'
-- Superuser (polaris): always bypasses, even with FORCE.
SELECT 'superuser polaris' AS identity, count(*) AS visible_rows FROM rls_demo.service_requests;

-- Table owner (non-superuser): bypasses RLS by default.
SET ROLE rls_table_owner;
SELECT rls_demo.set_tenant(1);
SELECT 'owner, RLS not forced' AS identity, count(*) AS visible_rows FROM rls_demo.service_requests;
RESET ROLE;

-- FORCE ROW LEVEL SECURITY makes policies apply to the owner too.  No policy targets
-- rls_table_owner, so the owner now sees nothing (default deny).
ALTER TABLE rls_demo.service_requests FORCE ROW LEVEL SECURITY;
SET ROLE rls_table_owner;
SELECT 'owner, RLS forced' AS identity, count(*) AS visible_rows FROM rls_demo.service_requests;
RESET ROLE;

-- row_security = off does NOT disable RLS for normal users: it raises an error
-- instead of silently returning filtered results (handy for pg_dump correctness).
SET ROLE rls_tenant_user;
SET row_security = off;
DO $$
BEGIN
    PERFORM count(*) FROM rls_demo.service_requests;
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'row_security=off for a non-bypass role: %', SQLERRM;
END $$;
RESET row_security;
RESET ROLE;

SELECT rolname, rolsuper, rolbypassrls
FROM pg_roles
WHERE rolname IN ('polaris', 'rls_tenant_user', 'rls_table_owner', 'rls_auditor')
ORDER BY rolname;

SELECT relname, relrowsecurity AS rls_enabled, relforcerowsecurity AS rls_forced
FROM pg_class
WHERE oid = 'rls_demo.service_requests'::regclass;

-- =============================================================================
-- 8. PITFALL: views run with the VIEW OWNER's rights (unless security_invoker)
-- =============================================================================
-- A view owned by the table owner (or a superuser) bypasses RLS for everyone who
-- can SELECT from the view.  PG15+ security_invoker = true checks policies as
-- the caller instead.
ALTER TABLE rls_demo.service_requests NO FORCE ROW LEVEL SECURITY;

CREATE VIEW rls_demo.v_requests_definer AS
    SELECT request_id, tenant_id, status FROM rls_demo.service_requests;
CREATE VIEW rls_demo.v_requests_invoker WITH (security_invoker = true) AS
    SELECT request_id, tenant_id, status FROM rls_demo.service_requests;
ALTER VIEW rls_demo.v_requests_definer OWNER TO rls_table_owner;
ALTER VIEW rls_demo.v_requests_invoker OWNER TO rls_table_owner;
GRANT SELECT ON rls_demo.v_requests_definer, rls_demo.v_requests_invoker TO rls_tenant_user;

SET ROLE rls_tenant_user;
SELECT rls_demo.set_tenant(1);
SELECT 'definer view (leaks!)'        AS via, count(*) AS visible_rows FROM rls_demo.v_requests_definer
UNION ALL
SELECT 'security_invoker view (safe)', count(*) FROM rls_demo.v_requests_invoker;
RESET ROLE;

-- =============================================================================
-- 9. RLS ON A SHARED BASE TABLE (rolled back): citizens see only themselves
-- =============================================================================
-- The original lesson: a citizen self-access policy on civics.citizens.
-- ENABLE RLS / CREATE POLICY are transactional, so the base table is untouched afterwards.
\echo '-- citizen self-access on civics.citizens (rolled back)'
BEGIN;
ALTER TABLE civics.citizens ENABLE ROW LEVEL SECURITY;

CREATE POLICY citizen_self_access ON civics.citizens
    FOR SELECT TO rls_tenant_user
    USING (citizen_id = NULLIF(current_setting('app.current_citizen_id', true), '')::BIGINT);

CREATE POLICY staff_full_access ON civics.citizens
    FOR SELECT TO rls_tenant_user
    USING (current_setting('app.user_role', true) IN ('staff', 'admin', 'supervisor'));

GRANT USAGE ON SCHEMA civics TO rls_tenant_user;
GRANT SELECT (citizen_id, first_name, last_name, status) ON civics.citizens TO rls_tenant_user;

SET LOCAL ROLE rls_tenant_user;
SELECT set_config('app.current_citizen_id', '42', true), set_config('app.user_role', 'citizen', true);
SELECT 'citizen #42' AS identity, count(*) AS visible_citizens,
       string_agg(first_name || ' ' || last_name, ', ') AS sample
FROM civics.citizens;

SELECT set_config('app.user_role', 'staff', true);
SELECT 'staff' AS identity, count(*) AS visible_citizens,
       count(*) FILTER (WHERE status = 'active') AS active_citizens
FROM civics.citizens;
ROLLBACK;

-- Verify the base table really is unchanged
SELECT relname, relrowsecurity AS rls_enabled_after_rollback,
       (SELECT count(*) FROM pg_policies WHERE schemaname = 'civics' AND tablename = 'citizens') AS policies
FROM pg_class WHERE oid = 'civics.citizens'::regclass;

-- =============================================================================
-- 10. REUSABLE CONTEXT FUNCTIONS (auth schema)
-- =============================================================================
-- Application-facing helpers that set/clear/read the RLS context in one call.
CREATE OR REPLACE FUNCTION auth.set_user_context(
    citizen_id         BIGINT  DEFAULT NULL,
    merchant_id        BIGINT  DEFAULT NULL,
    user_role          TEXT    DEFAULT 'citizen',
    staff_jurisdiction TEXT    DEFAULT NULL,
    tenant_id          INTEGER DEFAULT NULL,
    is_local           BOOLEAN DEFAULT false
)
RETURNS VOID AS $$
BEGIN
    PERFORM set_config('app.current_citizen_id',  COALESCE(citizen_id::TEXT, ''),  is_local);
    PERFORM set_config('app.current_merchant_id', COALESCE(merchant_id::TEXT, ''), is_local);
    PERFORM set_config('app.user_role',           COALESCE(user_role, ''),         is_local);
    PERFORM set_config('app.staff_jurisdiction',  COALESCE(staff_jurisdiction, ''), is_local);
    PERFORM set_config('app.current_tenant',      COALESCE(tenant_id::TEXT, ''),   is_local);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION auth.clear_user_context()
RETURNS VOID AS $$
BEGIN
    PERFORM set_config('app.current_citizen_id', '', false);
    PERFORM set_config('app.current_merchant_id', '', false);
    PERFORM set_config('app.user_role', '', false);
    PERFORM set_config('app.staff_jurisdiction', '', false);
    PERFORM set_config('app.current_tenant', '', false);
END;
$$ LANGUAGE plpgsql;

-- NULLIF guards against ''::BIGINT errors after the context was cleared
CREATE OR REPLACE FUNCTION auth.get_user_context()
RETURNS TABLE(
    citizen_id BIGINT,
    merchant_id BIGINT,
    user_role TEXT,
    staff_jurisdiction TEXT,
    tenant_id INTEGER
) AS $$
    SELECT
        NULLIF(current_setting('app.current_citizen_id', true), '')::BIGINT,
        NULLIF(current_setting('app.current_merchant_id', true), '')::BIGINT,
        NULLIF(current_setting('app.user_role', true), ''),
        NULLIF(current_setting('app.staff_jurisdiction', true), ''),
        NULLIF(current_setting('app.current_tenant', true), '')::INTEGER;
$$ LANGUAGE sql STABLE;

SELECT auth.set_user_context(citizen_id => 7, user_role => 'citizen', tenant_id => 2);
SELECT * FROM auth.get_user_context();
SELECT auth.clear_user_context();
SELECT * FROM auth.get_user_context();

-- Demo function: per-tenant visible counts, executed as the app role via SET ROLE
-- inside the caller (functions cannot SET ROLE themselves when SECURITY DEFINER).
CREATE OR REPLACE FUNCTION rls_demo.demo_tenant_visibility(p_tenants INTEGER[])
RETURNS TABLE(tenant_id INTEGER, visible_rows BIGINT, own_rows BIGINT)
LANGUAGE plpgsql AS $$
DECLARE t INTEGER;
BEGIN
    FOREACH t IN ARRAY p_tenants LOOP
        PERFORM rls_demo.set_tenant(t, true);
        RETURN QUERY
        SELECT t, count(*), count(*) FILTER (WHERE s.tenant_id = t)
        FROM rls_demo.service_requests s;
    END LOOP;
    PERFORM rls_demo.set_tenant(NULL, true);
END $$;
GRANT EXECUTE ON FUNCTION rls_demo.demo_tenant_visibility(INTEGER[]) TO rls_tenant_user;

BEGIN;
SET LOCAL ROLE rls_tenant_user;
SELECT * FROM rls_demo.demo_tenant_visibility(ARRAY[1, 2, 3]) ORDER BY tenant_id;
COMMIT;

-- Leave the session clean
SELECT auth.clear_user_context();
\echo '== RLS module complete =='
